FROM ghcr.io/pgedge/base-test-image:latest

ARG PGVER

ENV PGVER=$PGVER

WORKDIR /home/pgedge

RUN echo "Determine PostgreSQL tag"
RUN LATEST_TAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | \
				grep "refs/tags/REL_${PGVER}_" | \
				sed 's|.*refs/tags/||' | \
				tr '_' '.' | \
				sort -V | \
				tail -n 1 | \
				tr '.' '_') && \
			echo "Using tag $LATEST_TAG" && \
			git clone --branch $LATEST_TAG --depth 1 https://github.com/postgres/postgres /home/pgedge/postgres


RUN sudo chmod -R a+w ~/postgres

RUN echo "Setting up pgedge..."
WORKDIR /home/pgedge
RUN curl -fsSL https://pgedge-download.s3.amazonaws.com/REPO/install.py > /home/pgedge/install.py
RUN sudo -u pgedge python3 /home/pgedge/install.py

WORKDIR /home/pgedge/postgres

RUN for patchfile in /home/pgedge/spock/patches/${PGVER}/*; do \
		patch -p1 --verbose < $patchfile; \
	done

RUN echo "==========Compiling Modified PostgreSQL=========="
RUN options="'--prefix=/home/pgedge/pgedge/pg$PGVER' '--disable-rpath' '--with-zstd' '--with-lz4' '--with-icu' '--with-libxslt' '--with-libxml' '--with-uuid=ossp' '--with-gssapi' '--with-ldap' '--with-pam' '--enable-debug' '--enable-dtrace' '--with-llvm' 'LLVM_CONFIG=/usr/bin/llvm-config-64' '--with-openssl' '--with-systemd' '--enable-tap-tests' '--with-python' '--enable-cassert' 'PYTHON=/usr/bin/python3.9' 'BITCODE_CFLAGS=-gdwarf-5 -O0 -fforce-dwarf-frame' 'CFLAGS=-g -O0'" && eval ./configure $options && make -j4 && make install

WORKDIR /home/pgedge

RUN echo "export LD_LIBRARY_PATH=/home/pgedge/pgedge/pg$PGVER/lib/:$LD_LIBRARY_PATH" >> /home/pgedge/.bashrc
RUN echo "export PATH=/home/pgedge/pgedge/pg$PGVER/bin:$PATH" >> /home/pgedge/.bashrc

RUN echo "==========Recompiling Spock=========="
WORKDIR /home/pgedge/spock
RUN . /home/pgedge/.bashrc && export PG_CONFIG=/home/pgedge/pgedge/pg$PGVER/bin/pg_config && export PATH=/home/pgedge/pgedge/pg$PGVER/bin:$PATH && make clean && make -j16 && make install

RUN echo "==========Built Spock=========="

#-----------------------------------------
COPY tests/docker/entrypoint.sh tests/docker/run-tests.sh tests/docker/run-spock-regress.sh /home/pgedge

RUN sudo chmod +x /home/pgedge/entrypoint.sh /home/pgedge/run-tests.sh /home/pgedge/run-spock-regress.sh

WORKDIR /home/pgedge/
USER pgedge

CMD ["/home/pgedge/entrypoint.sh"]
