exclude_paths:
  - 'tests/regress/sql/*.sql'     # non-standard SQL files with \ directives
  - 'sql/*.sql' # non-standard SQL files with \ directives

# Ignore LOC and complexity for inherited files
engines:
  metric:
    exclude_paths:
      - "src/spock_apply.c"
      - "src/spock_apply_heap.c"
      - "src/spock_apply_spi.c"
      - "src/spock.c"
      - "src/spock_conflict.c"
      - "src/spock_dependency.c"
      - "src/spock_executor.c"
      - "src/spock_fe.c"
      - "src/spock_functions.c"
      - "src/spock_manager.c"
      - "src/spock_monitoring.c"
      - "src/spock_node.c"
      - "src/spock_output.c"
      - "src/spock_output_config.c"
      - "src/spock_output_plugin.c"
      - "src/spock_output_proto.c"
      - "src/spock_proto_json.c"
      - "src/spock_proto_native.c"
      - "src/spock_queue.c"
      - "src/spock_relcache.c"
      - "src/spock_repset.c"
      - "src/spock_rpc.c"
      - "src/spock_sequences.c"
      - "src/spock_sync.c"
      - "src/spock_worker.c"
  lizard:
    exclude_paths:
      - "src/spock_apply.c"
      - "src/spock_apply_heap.c"
      - "src/spock_apply_spi.c"
      - "src/spock.c"
      - "src/spock_conflict.c"
      - "src/spock_dependency.c"
      - "src/spock_executor.c"
      - "src/spock_fe.c"
      - "src/spock_functions.c"
      - "src/spock_manager.c"
      - "src/spock_monitoring.c"
      - "src/spock_node.c"
      - "src/spock_output.c"
      - "src/spock_output_config.c"
      - "src/spock_output_plugin.c"
      - "src/spock_output_proto.c"
      - "src/spock_proto_json.c"
      - "src/spock_proto_native.c"
      - "src/spock_queue.c"
      - "src/spock_relcache.c"
      - "src/spock_repset.c"
      - "src/spock_rpc.c"
      - "src/spock_sequences.c"
      - "src/spock_sync.c"
      - "src/spock_worker.c"
