FROM rockylinux:9

ARG PGVER

ENV PGVER=$PGVER

RUN dnf -y update && dnf -y install sudo && dnf -y groupinstall "Development Tools"

RUN useradd -m pgedge -s /bin/bash && \
    echo pgedge:asdf | chpasswd && \
    echo "pgedge ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/pgedge && \
    chmod 0440 /etc/sudoers.d/pgedge && \
    chown -R pgedge:pgedge /home/pgedge

COPY tests/lib-list.txt /home/pgedge/

RUN dnf install --allowerasing --enablerepo=crb -y $(cat /home/pgedge/lib-list.txt)

RUN ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519 && \
    cat ~/.ssh/*.pub >> ~/.ssh/authorized_keys


COPY . /home/pgedge/spock
RUN chown -R pgedge:pgedge /home/pgedge/spock
#-----------------------------------------
USER pgedge


WORKDIR /home/pgedge

RUN echo "Determine PostgreSQL tag"
RUN LATEST_TAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | \
				grep "refs/tags/REL_${PGVER}_" | \
				sed 's|.*refs/tags/||' | \
				tr '_' '.' | \
				sort -V | \
				tail -n 1 | \
				tr '.' '_') && \
			echo "Using tag $LATEST_TAG" && \
			git clone --branch $LATEST_TAG --depth 1 https://github.com/postgres/postgres /home/pgedge/postgres


RUN sudo chmod -R a+w ~/postgres

RUN echo "Setting up pgedge..."
WORKDIR /home/pgedge
RUN curl -fsSL https://pgedge-download.s3.amazonaws.com/REPO/install.py > /home/pgedge/install.py
RUN sudo -u pgedge python3 /home/pgedge/install.py

WORKDIR /home/pgedge/postgres

RUN git apply --verbose /home/pgedge/spock/patches/pg${PGVER}*

RUN echo "==========Compiling Modified PostgreSQL=========="
RUN options="'--prefix=/home/pgedge/pgedge/pg$PGVER' '--disable-rpath' '--with-zstd' '--with-lz4' '--with-icu' '--with-libxslt' '--with-libxml' '--with-uuid=ossp' '--with-gssapi' '--with-ldap' '--with-pam' '--enable-debug' '--enable-dtrace' '--with-llvm' 'LLVM_CONFIG=/usr/bin/llvm-config-64' '--with-openssl' '--with-systemd' '--enable-tap-tests' '--with-python' 'PYTHON=/usr/bin/python3.9' 'BITCODE_CFLAGS=-gdwarf-5 -O0 -fforce-dwarf-frame' 'CFLAGS=-g -O0'" && eval ./configure $options && make -j4 && make install

WORKDIR /home/pgedge

RUN echo "export LD_LIBRARY_PATH=/home/pgedge/pgedge/pg$PGVER/lib/:$LD_LIBRARY_PATH" >> /home/pgedge/.bashrc
RUN echo "export PATH=/home/pgedge/pgedge/pg$PGVER/bin:$PATH" >> /home/pgedge/.bashrc

RUN echo "==========Recompiling Spock=========="
WORKDIR /home/pgedge/spock
RUN . /home/pgedge/.bashrc && export PG_CONFIG=/home/pgedge/pgedge/pg$PGVER/bin/pg_config && export PATH=/home/pgedge/pgedge/pg$PGVER/bin:$PATH && make clean && make -j16 && make install

RUN echo "==========Built Spock=========="

#-----------------------------------------
COPY tests/entrypoint.sh tests/run-tests.sh tests/run-spock-regress.sh /home/pgedge

RUN sudo chmod +x /home/pgedge/entrypoint.sh /home/pgedge/run-tests.sh /home/pgedge/run-spock-regress.sh

WORKDIR /home/pgedge/
USER pgedge

CMD ["/home/pgedge/entrypoint.sh"]
